add check to ensure the needed pod has been discovered if the loop times out
Signed-off-by: Daniel Kiptoon <kiptoonkipkurui@gmail.com>

diff --git a/.github/workflows/e2etests.yml b/.github/workflows/e2etests.yml
--- a/.github/workflows/e2etests.yml
+++ b/.github/workflows/e2etests.yml
@@ -151,4 +151,10 @@ jobs:
               break           
             fi
           done
+
+          # Check if the loop completed its iterations without finding a match
+          if [ -z "$result" ]; then
+              echo "Error: MeshSync unable to discover resources."
+              exit 1
+          fi
         shell: bash
